### ISSUE TITLE
Dotnet 3.1.426

### ISSUE THREAD

**Issue by gabrieligbastos** [hensou/asdf-dotnet#40] opened 2024-07-01 14:29 UTC
**Describe the bug**

Not installing dotnet 3.1.426

**Steps to reproduce**

dotnet install dotnet 3.1.426

**Expected behavior**

To install

**Screenshots**

```
❯ asdf install dotnet 3.1.426
* Downloading dotnet installer...
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 1: !DOCTYPE: No such file or directory
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 2: html: No such file or directory
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 3: head: No such file or directory
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 4: meta: No such file or directory
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 5: title: No such file or directory
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 6: style: No such file or directory
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 7: body: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 8: font-family:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 8:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 9: font-size:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 9:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 10: color:: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 11: background-color:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 12: }
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 13:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 14: h1,: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 15: /*font-family:: No such file or directory
: No such file or directoryads/dotnet/3.1.426/dotnet-install.sh: line 15: */
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 16: font-weight:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 16:
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 17: }
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 18:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 19: h1: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 20: color:: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 21: margin:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 21:
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 22: }
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 23:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 24: h2: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 25: margin:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 25:
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 26: }
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 27:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 28: h3: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 29: color:: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 30: margin:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 30:
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 31: }
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 32:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 34: font-family:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 34:
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 35: }
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 36:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 37: body: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 38: padding:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 38:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 39: display:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 39:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 40: font-size:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 40:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 41: font-weight:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 41:
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 42: }
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 43:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 44: a: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 45: color:: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 46: text-decoration:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 46:
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 47: }
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 48:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 49: a:hover: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 50: color:: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 51: text-decoration:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 51:
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 52: }
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 53:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 54: li: command not found
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 55: margin:: command not found
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 55:
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 56: }
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 57:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 58: /style: No such file or directory
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 59: /head: No such file or directory
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 60: body: No such file or directory
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 61: h1: No such file or directory
: command not foundf/downloads/dotnet/3.1.426/dotnet-install.sh: line 62:
/Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 63: syntax error near unexpected token `<'
'Users/{my_user_name}/.asdf/downloads/dotnet/3.1.426/dotnet-install.sh: line 63: `        <h2> Common solutions to this issue: </h2><ul><li>The app failed to start</li><li>The app started but then stopped</li><li>The app started but threw an exception during startup</li></ul>
asdf-dotnet: Expected /Users/{my_user_name}/.asdf/installs/dotnet/3.1.426/bin/dotnet to be executable.
asdf-dotnet: An error ocurred while installing dotnet 3.1.426.
```

**Additional context**

any clue on how to install any 3.1 dotnet ?

**Comment by hensou** [comment] 2024-07-01 15:02
@gabrieligbastos that is likely because [microsoft's installer script](https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh) is throwing a 500 at the moment.

Currently we download the latest version of this script at the moment of installation. Maybe we can improve that by caching the latest version as well.

But for now I would suggest you to wait for some hours, hopefully it will get fixed soon.

![image](https://github.com/hensou/asdf-dotnet/assets/1756077/420cd4ad-d78d-42c0-ac28-ad7562436629)

**Comment by hensou** [comment] 2024-07-01 15:04
We can also improve the error handling here to show a better error message when this happens.

**Comment by gabrieligbastos** [comment] 2024-07-01 16:44
Oh, you were right! Now, it is back. Thanks
Yeah, probably those caching and better error handling would be great :)

How would that cache be?

**Comment by hensou** [comment] 2024-07-01 17:02
> Oh, you were right! Now, it is back. Thanks Yeah, probably those caching and better error handling would be great :)
> 
> How would that cache be?

That's nice! Great that it is working again :)

So that "caching" could be achieved just by removing this line https://github.com/hensou/asdf-dotnet/blob/6a2425fc2215a01fa202d7ab2daad82251bee4fc/lib/utils.bash#L52 .
I haven't given too much thought too it, but I think it would just work.

I have to think more about it.

**Comment by hensou** [comment] 2024-07-03 11:37
Closing this as it was not a bug on our side. However I created two other issues for better error handling and caching.

**Closed by hensou** 2024-07-03 11:37 UTC
Labels: bug
